sonar.project.key=drokade981_mern-auth-service
sornar.organization=drokade981

sonar.projectName=mern-auth-service

sonar.sources=src

sonar.tests=tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*migration/**/*

sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.scm.exclusions.disabled=true